apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ksm-fuse-online-alerts
  namespace: {{ index .Params "Namespace" }}
spec:
  groups:
    - name: fuseOnline.rules
      rules:
        - alert: FuseOnlineSyndesisServerInstanceDown
          annotations:
            sop_url: https://github.com/RHCloudServices/integreatly-help/blob/master/sops/alerts_and_troubleshooting.md
            message: >-
              Fuse Online Syndesis Server instance {{ "{{" }}$labels.pod{{ "}}" }} in namespace {{ "{{" }}$labels.namespace{{ "}}" }} is down.
          expr: |
            (1 - absent(kube_pod_status_ready{condition="true",namespace="{{ index .Params "Namespace" }}"} * on (pod, namespace) kube_pod_labels{label_deploymentconfig="syndesis-server"})) or sum(kube_pod_status_ready{condition="true",namespace="{{ index .Params "Namespace" }}"} * on (pod, namespace) kube_pod_labels{label_deploymentconfig="syndesis-server"}) < 1
          for: 5m
          labels:
            severity: critical
        - alert: FuseOnlineSyndesisUIInstanceDown
          annotations:
            sop_url: https://github.com/RHCloudServices/integreatly-help/blob/master/sops/alerts_and_troubleshooting.md
            message: >-
              Fuse Online Syndesis UI instance {{ "{{" }}$labels.pod{{ "}}" }} in namespace {{ "{{" }}$labels.namespace{{ "}}" }} is down.
          expr: |
            (1 - absent(kube_pod_status_ready{condition="true",namespace="{{ index .Params "Namespace" }}"} * on (pod, namespace) kube_pod_labels{label_deploymentconfig="syndesis-ui"})) or sum(kube_pod_status_ready{condition="true",namespace="{{ index .Params "Namespace" }}"} * on (pod, namespace) kube_pod_labels{label_deploymentconfig="syndesis-ui"}) < 1
          for: 5m
          labels:
            severity: critical